services:
  nginx:
    volumes:
      - ./nginx/ft_prodd.dev.conf:/etc/nginx/conf.d/ft_prodd.conf:ro

  backend:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ../backend:/app
      - ../websocket:/app/src/ws
      - /app/node_modules
    command: ["sh", "-c", "npx prisma db push && npx tsx watch src/index.ts"]

  frontend:
    build:
      target: development
    environment:
      NODE_ENV: development
      VITE_API_URL: /
      VITE_UPLOADS_PROXY: http://ft_prodd_backend:3001
    volumes:
      - ../frontend:/app
      - ../websocket:/app/src/ws
      - /app/node_modules
    ports:
      - "3456:3000"
    stdin_open: true
    tty: true
